---
title: "useR! 2021"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    self_contained: false
    includes:
      after_body: "afterInit.html"
      #beforeInit: "afterInit.html"
      
    css: css/custom.css
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(stringr)
library(countrycode)
library(reactable)
library(htmltools)
library(echarts4r)
library(lubridate)
source("events_summary.R")
```

Sidebar {.sidebar data-width=200}
=====================================

<div class="sidebar-pages">
<a class="navlink" href="#home" data-toggle="tab" aria-expanded="false"><i class="fa fa-home"></i> The R Conference</a>
</div>

The R Conference
=====================================

Row
-------------------------------------

### Total Presentations

```{r}
valueBox(no_of_sess, icon = "fa-video", color = "#435f9c")
```

### Total Authors

```{r}
valueBox(number_of_speakers, icon = "fa-user-edit", color = "#0586c4")
```

### Total Participants

```{r}
valueBox(total_ptps, icon = "fa-handshake", color = "#435f9c")
```

### Total Countries

```{r}
valueBox(total_ctry, icon = "fa-globe", color = "#0586c4")
```

Row {data-height=400}
-----------------------------------------------------------------------

### World Map | <small> Cumulative Registrations </small>

```{r}
wmap_ptp_df %>% e_country_names(country) %>% 
  e_charts(country) %>%
  e_map(Count, roam = TRUE, zoom = 1) %>%
  e_visual_map(min =0, max = max(wmap_ptp_df$Count), 
               color = c("#00438D","#195598",
                         "#3268a3", "#4c7baf",
                         "#668eba","#7fa1c6",
                         "#99b3d1", "#b2c6dc",
                         "#ccd9e8", "#e5ecf3",
                         "#ffffff")) %>% 
  e_tooltip() %>%
  e_title("Registrations", "Timeline") 
```

### Registrations per Day

```{r}
mycolor <- c("#4ca0c6","#003636","#a9a9a9", "#91c8c8")
cum_time_df %>% 
  e_charts(registration_date) %>% 
  e_line(Registration_Count) %>%
  e_title(text = "Registrations", 
          subtext = "Timeline", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 0,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

<!-- Row {data-height=550} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### Timeline Mapping | <small> Registrations per Day per Country </small> -->

<!-- ```{r} -->
<!-- mycolor <- c("#4ca0c6","#003636","#a9a9a9", "#91c8c8") -->
<!-- time_df %>%  -->
<!--   group_by(country) %>% -->
<!--   e_charts(registration_date,timeline = TRUE) %>%  -->
<!--   e_area(Count) %>% -->
<!--   e_title(text = "Registrations",  -->
<!--           subtext = "Timeline",  -->
<!--           sublink = "#", -->
<!--           left = "left", top = 4 -->
<!--   ) %>% -->
<!--   e_y_axis( -->
<!--     splitArea = list(show = TRUE), -->
<!--     axisPointer = list(      show = FALSE,  -->
<!--                              lineStyle = list( -->
<!--                                color = "#999999", -->
<!--                                width = 0.75, -->
<!--                                type = "dotted" -->
<!--                              )) -->
<!--   ) %>% -->
<!--   e_x_axis(splitArea = list(show = TRUE), -->
<!--            splitLine = list(show = TRUE), -->
<!--            axisLabel= list(rotate = 0,interval = 0)) %>% -->
<!--   e_toolbox_feature(feature = "magicType", -->
<!--                     type = list("area", "line", "bar")) %>% -->
<!--   e_toolbox_feature("restore") %>% -->
<!--   e_toolbox_feature(feature = "reset") %>% -->
<!--   e_toolbox_feature("dataView") %>% -->
<!--   e_toolbox_feature("saveAsImage") %>% -->
<!--   e_animation(duration = 1000) %>% -->
<!--   e_timeline_opts( -->
<!--     axis_type = "category", -->
<!--     playInterval = 1500, -->
<!--     top = 10, -->
<!--     right = 80, -->
<!--     left = 100 -->
<!--   ) %>% -->
<!--   e_tooltip(trigger = "axis") %>% e_color(mycolor) -->
<!-- ``` -->

Row {data-height=450}
-----------------------------------------------------------------------

### Event Categories | <small> Summaries </small>

```{r}
smry_calendar %>%
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    defaultSorted = "Count",
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      Name = colDef(
        name = "Calendar Name",
        width = 180,
        defaultSortOrder = "desc",
        filterable = TRUE,
      ),
      Count = colDef(
        name = "Frequency",
        defaultSortOrder = "desc",
        cell = function(value) {
          width <- paste0(value * 100 / max(smry_calendar$Count), "%")
          value <- format(value, big.mark = ",")
          value <- format(value, width = 9, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "6px"),
            div(class = "bar", style = list(width = width, backgroundColor = "#fc5185"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      )),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```

### Tags | <small> Ranked by Most popular </small>

```{r}
tagsdf %>%
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    defaultSorted = "Count",
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      Tags = colDef(
        name = "Tag Name",
        width = 200,
        defaultSortOrder = "desc",
        filterable = TRUE,
      ),
      Count = colDef(
        name = "Frequency",
        defaultSortOrder = "desc",
        cell = function(value) {
          width <- paste0(value * 100 / max(tagsdf$Count), "%")
          value <- format(value, big.mark = ",")
          value <- format(value, width = 9, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "6px"),
            div(class = "bar", style = list(width = width, backgroundColor = "#fc5185"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      )),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```

### Participating Countries | <small> Registrations per Country</small>

```{r}
ctry_ptp_df %>%
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    defaultSorted = "Count",
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      country = colDef(
        name = "Country",
        width = 150,
        defaultSortOrder = "desc",
        filterable = TRUE,
      ),
      Count = colDef(
        name = "Participation Frequency",
        defaultSortOrder = "desc",
        cell = function(value) {
          width <- paste0(value * 100 / max(ctry_ptp_df$Count), "%")
          value <- format(value, big.mark = ",")
          value <- format(value, width = 9, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "6px"),
            div(class = "bar", style = list(width = width, backgroundColor = "#fc5185"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      )),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```

Row {data-height=550}
-----------------------------------------------------------------------

### Presentation Datatable | <small> useR! 2021 <small> 

```{r}
select(event_df, -c(6, 8:13, 15:16, 19)) %>% 
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    style = list(fontFamily = 'Menlo',
                 fontSize = '14px'),
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      Subject = colDef(
        name = "Title",
        width = 200,
        defaultSortOrder = "desc",
        filterable = TRUE
      ),
      Start.Date = colDef(
        name = "Start Date",
        filterable = TRUE
      ),
      Start.Time = colDef(
        name = "Start Time",
        width = 50
      ),
      End.Date = colDef(
        name = "End Date"
      ),
      End.Time = colDef(
        name = "End Time",
        width = 50
      ),
      Calendar.Name = colDef(
        name = "Calendar Name",
        width = 100
      ),
      Who = colDef(
        name = "Presenters",
        filterable = TRUE
      ),
      Tags = colDef(
        name = "Tag Name",
        filterable = TRUE
      ),
      Session.name = colDef(
        name = "Session Name",
        width = 120
      )
    ),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```

Row
-------------------------------------

### Total Tutorials

```{r}
valueBox(no_of_tut, icon = "fa-slideshare", color = "#0586c4")
```

### Total Instructors

```{r}
valueBox(no_of_instr, icon = "fa-chalkboard-teacher", color = "#435f9c")
```

### Average Tutorial Duration

```{r}
valueBox(avg_tut_duration, icon = "fa-hourglass-half", color = "#0586c4")
```

### Average Tutorial Attendees

```{r}
valueBox(avg_tut_attendees, icon = "fa-users", color = "#435f9c")
```

### Tutorial Languages

```{r}
valueBox(lang_count, icon = "fa-language", color = "#0586c4")
```

Row {data-height=450}
-----------------------------------------------------------------------

### Tutorial Datatable | <small> useR! 2021 <small> 

```{r}
select(tutorials_df, -c(1:2, 8, 11:12)) %>% 
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    style = list(fontFamily = 'Menlo',
                 fontSize = '14px'),
    defaultSorted = "attendees",
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      title = colDef(
        name = "Tutorial Title",
        width = 200,
        defaultSortOrder = "desc",
        filterable = TRUE,
        html = TRUE,
        cell = function(value, index) {
          sprintf('<a href="%s" target="_blank">%s</a>', tutorials_df$individual_links[index], value)
        }
      ),
      language = colDef(
        name = "Language",
        filterable = TRUE,
        width = 100
      ),
      start = colDef(
        name = "Start Time",
        width = 100
      ),
      end = colDef(
        name = "End Time",
        width = 100
      ),
      instructors = colDef(
        name = "Instructors",
        filterable = TRUE
      ),
      duration = colDef(
        name = "Duration",
        width = 80
      ),
      attendees = colDef(
        name = "Attendees Count",
        defaultSortOrder = "desc",
        cell = function(value) {
          width <- paste0(value * 100 / max(tutorials_df$attendees), "%")
          value <- format(value, big.mark = ",")
          value <- format(value, width = 9, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "6px"),
            div(class = "bar", style = list(width = width, backgroundColor = "#fc5185"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      )
    ),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```

